// Build step: encode the portfolio's real images to base64 and inline them
// into a single code.js, because a Figma plugin manifest points at one file.
//
//   node figma-plugin/build.mjs
//
import sharp from 'sharp'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')

const IMAGES = [
  { key: 'wave', file: 'public/Layer_1 1.png', width: 700, format: 'png' },
  { key: 'openchantier', file: 'public/openchantier_project.png', width: 900, format: 'jpeg' },
  { key: 'sfk', file: 'public/SFK.jpg', width: 900, format: 'jpeg' },
]

const entries = []
for (const img of IMAGES) {
  const pipeline = sharp(join(root, img.file)).resize({ width: img.width, withoutEnlargement: true })
  const buf = img.format === 'png'
    ? await pipeline.png({ compressionLevel: 9, palette: true, quality: 90 }).toBuffer()
    : await pipeline.flatten({ background: '#0A0A0B' }).jpeg({ quality: 78, mozjpeg: true }).toBuffer()
  const meta = await sharp(buf).metadata()
  entries.push(`  ${img.key}: { w: ${meta.width}, h: ${meta.height}, b64: "${buf.toString('base64')}" }`)
  console.log(`${img.key.padEnd(14)} ${meta.width}x${meta.height}  ${(buf.length / 1024).toFixed(0)} KB`)
}

const assets = `// GENERATED by build.mjs — do not edit by hand.\nconst ASSETS = {\n${entries.join(',\n')}\n}\n`
await writeFile(join(here, 'src', 'assets.js'), assets)

const main = await readFile(join(here, 'src', 'main.js'), 'utf8')
await writeFile(join(here, 'code.js'), `${assets}\n${main}`)
console.log('\nwrote figma-plugin/code.js')
